version: '3'

services:
  flask:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./python3-saml/demo-flask:/demo-flask"
    tty: true
    environment:
      TZ: Asia/Tokyo

  https-portal:
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: "localhost -> http://flask:8000"
      STAGE: "local"
    volumes:
      - ./docker/https-portal:/var/lib/https-portal