version: '3'

services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
    - ./src:/var/www

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 8080:80
    volumes:
    - ./src:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/init:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
