version: "3"

services:
  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www

  nginx:
    image: nginx
    # ports:
    #   - 8080:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  https-portal:
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      # DOMAINS: "your.domain -> http://nginx"
      # STAGE: "production"
      # FORCE_RENEW: 'true'
      DOMAINS: "localhost -> http://nginx"
      STAGE: "local"
    volumes:
      - ./docker/https-portal:/var/lib/https-portal

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/conf:/etc/mysql/conf.d
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d

  # in local redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data

  # in local minio(S3)
  minio:
    image: minio/minio:latest
    ports:
      - 19000:9000
    volumes:
      - ./docker/minio/data:/export
      - ./docker/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: access
      MINIO_SECRET_KEY: password
    command: server /export

  # in local mailhog
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
